name: ${{github.workflow}}

on: workflow_dispatch

jobs:

  the_job:

    runs-on: ubuntu-latest
    # runs-on: windows-latest

    steps:

      # From https://manski.net/articles/github/actions/dump-context
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT_JSON: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT_JSON"
